services:
  surrealdb:
    image: surrealdb/surrealdb:v2.2.1
    container_name: surrealdb
    ports:
      - "8000:8000"
    command:
      - start
      - memory
      - -A
      - --no-banner
      - --user=root
      - --pass=root

    environment:
      SURREAL_LOG: info # none, full, error, warn, info, debug, trace
