name: Publish to JSR
on:
  push:
    tags:
      - "v*"

jobs:
  publish_jsr:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # - uses: denoland/setup-deno@v2
      #   with:
      #     deno-version: v2.x
      #
      # - name: Install dependencies
      #   run: deno install
      #
      # - name: Publish package
      #   run: deno publish

  publish_npm:
    runs-on: ubuntu-latest
    needs: [publish_jsr]

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # - name: Install dependencies
      #   run: deno install

      - name: Build
        run: deno run -A scripts/build_npm.ts
      - run: cd npm

      - run: echo $PWD
      - run: ls -l

      # - name: Setup node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #
      # - run: npm ci
      # - run: npm publish --provenance --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
